[package]
name = "mpvtester"
version = "0.1.0"
authors = ["Rex <elsecaller@8176135.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmpv = { path = "libmpv-rs", features = ["build_libmpv"] }
winit = "*"
winapi = "*"
pixels = "*"